mongo --eval "use BlackWatch"
mongo --eval "db.createCollection('BlackWatch')"
mongo --eval "db.createCollection('WatchList')"
mongo --eval "db.createCollection('Prison')"
mongo --eval "use Configuration"
mongo --eval "db.createCollection('DetectionPoints')"
mongo --eval "dp1 = {dpName : 'HTTP Verb', Limit : '2', Period : '60', Severity : 'Low'}"
mongo --eval "dp2 = {dpName : 'Login Page', Limit : '3', Period : '30', Severity : 'Low'}"
mongo --eval "db.DetectionPoints.insert(dp1)"
mongo --eval "db.DetectionPoints.insert(dp2)"
